### ISSUE TITLE
Mod stops the live game output option from working

### ISSUE THREAD

**Issue by NanashiTheNameless** [Pixelstormer/better_log4j_config#4]
When enabled the mod stops the live game output option from working. it doesn't update live until the game is closed, is there any way to fix this?

**Comment by BigWingBeat** [comment]
If you are using the vanilla launcher, this issue can be fixed by replacing the contents of the Console appender with `<LegacyXMLLayout />` in the mod's config file. Alternatively, you can use an alternate launcher that does not have this issue to begin with, such as [MultiMC](https://multimc.org/). I can't release a new version of the mod with this fix included by default however, as the legacy XML layout breaks the logging of non-vanilla launchers (Such as MultiMC).

Specifically, to fix the issue, look for the lines `<Console name="SysOut" target="SYSTEM_OUT">` and `</Console>` in the mod's config file. Then, replace everything in-between those lines with just `<LegacyXMLLayout />`.
